name: mi_n
channels:
  - conda-forge
dependencies:
  - poppler
  - pip:
    - streamlit>=1.8.1
    - pytesseract==0.3.9
    - pdf2image==1.16.0
    - Pillow==9.0.1
    - wordcloud==1.8.1
    - pdfplumber==0.6.0
